#!/bin/sh

DST=$1
SOUNDSFOLDER=SOUNDSFOLDERPLACEHOLDER

if [ $DST eq "" ]; then DST="./"; fi

mkdir -p $SOUNDSFOLDER
for file in $1/*.wav ; do
    F=`basename $file`
    sox -V $file -r 44100 -c 2 -b 16 -t wav $SOUNDSFOLDER/${F%.wav}-s16.wav
    sox -V $file -r 8000 -c 1 -t wav -e u-law $SOUNDSFOLDER/${F%.wav}-ulaw.wav
done
